package cz.cvut.fit.vybirjan.mp.common.comm;

public enum ResponseType {
	OK_EXISTING_VERIFIED,
	OK_NEW_CREATED,
	ERROR_NEW_ACTIVATIONS_NOT_ALLOWED,
	ERROR_INACTIVE,
	ERROR_INTERNAL_ERROR,
	ERROR_TOO_MANY_ACTIVATIONS,
	ERROR_LICENSE_NOT_FOUND,
	ERROR_EXPIRED
}